// Code generated by Kitex v0.8.0. DO NOT EDIT.

package uuidgeneratorserver

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	server0 "uuid_client/kitex_gen/uuid/generator/server"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetUUIDBounds(ctx context.Context, req *server0.GetUUIDBoundsRequest, callOptions ...callopt.Option) (r *server0.GetUUIDBoundsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUUIDGeneratorServerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUUIDGeneratorServerClient struct {
	*kClient
}

func (p *kUUIDGeneratorServerClient) GetUUIDBounds(ctx context.Context, req *server0.GetUUIDBoundsRequest, callOptions ...callopt.Option) (r *server0.GetUUIDBoundsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUUIDBounds(ctx, req)
}
